version: 2
updates:
- package-ecosystem: mix
  directory: "/nerves_key_quickstart_fw"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nerves
    versions:
    - 1.7.4
